# h/t https://github.com/jonchang/homebrew-tap/blob/main/.github/workflows/bump.yml
name: bump version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Homebrew/actions/setup-homebrew@master
    - uses: teaxyz/setup@v0

    - run: .github/actions/bump.ts
      env:
        TAP: teaxyz/pkgs

    - name: test `brew install`
      run: brew install ./tea-cli.rb

    - name: git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
